server:
  port: 8080 #端口号

spring:
  application:
    name: Animal_Center_Cage_Management_System #服务名称
  datasource: #数据库连接信息
    url: jdbc:mysql://localhost:3306/anping?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Qh123456789!
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


  freemarker:
    enabled: true
    suffix: .ftl
    expose-spring-macro-helpers: true
    template-loader-path: classpath:/templates/

#xml文件所在地址
mybatis-plus:
  mapper-locations: classpath:xml/*.xml

swagger:
  enabled: true

